### ISSUE TITLE
Platform/Instrument/Sensor variables

### ISSUE THREAD

**Issue by n-a-t-e** [cioos-siooc/metadata-xml#10]
Since there can be multiple instruments, as well as multiple sensors nested within each instrument, I have structured the instrument/sensor variable names as followed:

`instrument_1_id`
`instrument_1_version`
`instrument_1_description`

`instrument_1_sensor_1_id`
`instrument_1_sensor_1_version`
`instrument_1_sensor_1_description`

Also, I assumed that there can be only one platform, and the nesting goes Platform->Instrument->Sensor

This could work for now but I'm open to other ways of describing this metadata that work with pulling it from ERDDAP

**Comment by jeffcullis** [comment]
Brad mentioned that nested attributes are possible within NetCDF, e.g.:
https://gliders.ioos.us/erddap/tabledap/bass-20160909T1733.html
though I haven't seen an example where the global attributes are nested. Creating nested variables fo the instrument and sensor would be great if possible, but if it isn't possible then your solution seems like the only way to proceed.

**Comment by n-a-t-e** [comment]
this issue no longer relevant since switching from acdd type structure
