### ISSUE TITLE
Ensure yaml files don't break lxml with syntax error

### ISSUE THREAD

**Issue by jacobthompson101** [cioos-siooc/metadata-xml#16]
Special characters can break our yaml file, an easy fix might be to use single quotes, but that still means we have to ensure we cover all possible ways yaml can break so that we can write our xml files as expected.

I wrote a minimal/basic unit test on the branch [unittest-break-yamlformat](https://github.com/cioos-siooc/metadata-xml/tree/unittest-break-yamlformat) to validate that special characters do break the xml generation stage (step before writing). It's not a pretty test, but uses Faker and StringGenerator to mock up some fake data using the structure from the record_blank.yaml file. This can be expanded upon to more realistically test our process, and potentially a version of it could use similar logic to mock up a bunch of data if needed.

I don't know with certainty that using single quotes alone will be enough, hence the start of this test being written. The following describes the constraints: https://yaml.org/spec/1.2/spec.html#id2788097

**Comment by n-a-t-e** [comment]
Yes we will need to escape those characters, there is an `escape()`function included in the `xml` package that handles this well, just tried it out with branch `handle-special-chars-in-record`, see https://github.com/cioos-siooc/metadata-xml/compare/handle-special-chars-in-record?expand=1

**Comment by n-a-t-e** [comment]
Closing this, I think special characters are being handled
