### ISSUE TITLE
MI_Metadata vs MD_Metadata

### ISSUE THREAD

**Issue by n-a-t-e** [cioos-siooc/metadata-xml#3]
I see that the metadata team is using MI_Metadata but that element doesn't exist in the schema  we're using. Anyone know why we are using MI?

https://github.com/cioos-siooc/metadata-xml/blob/d3b915221124e6c83cfd2be3c0c9abc74354dcce/xml/cioos_template.xml#L2

**Comment by fostermh** [comment]
I found this earlier today, not sure if it's why but helps explain the
difference.

https://geo-ide.noaa.gov/wiki/index.php?title=ISO_FAQ#What_is_the_difference_between_MD_Metadata_and_MI_Metadata.3F

Matthew Foster
Hakai Institute, Calvert Island, BC, Canada / www.hakai.org
Tula Foundation, Quadra Island, BC, Canada / www.tula.org

**Comment by n-a-t-e** [comment]
Thanks for the link. Still not sure how to use `MI_Metadata` in a way that will validate as it complains that the tag `mdb:MI_Metadata` doesn't exist. Maybe it should be `gmi:MI_Metadata`, but not sure how that `gmi` fits in

**Comment by jeffcullis** [comment]
Interesting that the only thing under '-2' directory from https://standards.iso.org/iso/19115/ is the gmi namespace. I think you're right Nate that it should be gmi:MI_Metadata. I created a branch 'mi_metadata_validation' and took a shot at setting that up the way I think it should work. Not sure whether it will validate now but worth a try.

It seems we might be hampered here by the fact that latest ISO19115-2 is from 2019 while latest ISO19115-3 XML spec is from 2016 and doesn't show anything relating to proper use of MI_Metadata to add acquisitionInformation to MD_Metadata.

**Comment by jeffcullis** [comment]
Also, the file:
https://standards.iso.org/iso/19115/-2/gmi/1.0/metadataEntitySet.xsd
shows explicitly how MI_Metadata extends MD_Metadata by adding the acquisitionInformation element to it, but my XML knowledge is fairly limited for making use of this to get the XML template to validate.

**Comment by n-a-t-e** [comment]
I changed it back to MD_Metadata for now to get the XML validating

**Comment by n-a-t-e** [comment]
Closing until someone shows that we can make `MI_Metadata` work with our profile and pass xml validation
