### ISSUE TITLE
EX_VerticalExtent: verticalCRSId vs verticalCRS

### ISSUE THREAD

**Issue by fostermh** [cioos-siooc/metadata-xml#34]
currently in the template we hardcode verticalCRS as EPSG::5831 [L548](https://github.com/cioos-siooc/metadata-xml/blob/192130b74ae75c466edf74166a649e9998bccba5/metadata_xml/cioos_template.jinja2#L548) which is "instantaneous water level depth". verticalCRSId -> MD_ReferenceSystem is mandatory and hardcoded to "vertical" [L541](https://github.com/cioos-siooc/metadata-xml/blob/192130b74ae75c466edf74166a649e9998bccba5/metadata_xml/cioos_template.jinja2#L541) in the cioos metadata schema and verticalCRSId ->referenceSystemIdentifier is optional [L519](https://github.com/cioos-siooc/metadata-xml/blob/192130b74ae75c466edf74166a649e9998bccba5/metadata_xml/cioos_template.jinja2#L519). Given that we hard code referenceSystemIdentifier to EPSG::5831 does it makes sense for it to be mandatory?

**Comment by fostermh** [comment]
related to issue #12

**Comment by jeffcullis** [comment]
This makes sense to me. I suppose a counter-argument could be that EPSG::5831 should just be assumed if the referenceSystemIdentifier is not present. However it seems like an important enough field that ensuring it is always present is probably a good idea. I'll try to see what the metadata group thinks of this change.

**Comment by n-a-t-e** [comment]
this was fixed by #64
