### ISSUE TITLE
instrument mountedon

### ISSUE THREAD

**Issue by fostermh** [cioos-siooc/metadata-xml#36]
in iso schema mountedon [L993](https://github.com/cioos-siooc/metadata-xml/blob/192130b74ae75c466edf74166a649e9998bccba5/metadata_xml/cioos_template.jinja2#L933) is indicated as option and is the platform the instrument is mounted on. as instrument is a child of platform in the template this field is likely not needed here. it is empty anyway. Perhaps it was added to pass validation?

**Comment by jeffcullis** [comment]
Yes as you say in #35, for CIOOS the platform should be at the top level if it exists, so mountedOn for instruments should not be necessary and I beleive it was removed from the CIOOS profile for that reason and should probably be deleted from the template as well.
