### ISSUE TITLE
is instrument sensor mandatory or optional

### ISSUE THREAD

**Issue by fostermh** [cioos-siooc/metadata-xml#37]
cioos metadata schema dosen't mention sensor and the iso standard indicates it's optional I think. in the template is is said to be mandatory [L935](https://github.com/cioos-siooc/metadata-xml/blob/192130b74ae75c466edf74166a649e9998bccba5/metadata_xml/cioos_template.jinja2#L935). Should it be indicated as optional?

**Comment by n-a-t-e** [comment]
Looks like `Sensor` is currently optional in the template despite that comment saying its mandatory. But you're right looks like it's been removed from the profile, in that case I suggest we remove it entirely to simplify things
