### ISSUE TITLE
instrument sensor hosted not needed?

### ISSUE THREAD

**Issue by fostermh** [cioos-siooc/metadata-xml#38]
as sensor is child of instrument and hosted indicates the instrument the sensor is on, does it make sense to have hosted tag at all? [L968](https://github.com/cioos-siooc/metadata-xml/blob/192130b74ae75c466edf74166a649e9998bccba5/metadata_xml/cioos_template.jinja2#L968). I think not my self.

**Comment by n-a-t-e** [comment]
Removing it sounds good to me
