### ISSUE TITLE
allow contributor_name, contributor_role to be lists

### ISSUE THREAD

**Issue by n-a-t-e** [cioos-siooc/metadata-xml#53]
`contributor_name` and `contributor_role` should allow for a list of names, according to ACDD. The order of this list should be the same and the lists should be the same length

eg:
`contributor_name="A,B,C"`
`contributor_role="contributor, sponsor, funder" `

If the lists are different lengths it would throw an error

See http://wiki.esipfed.org/index.php/Attribute_Convention_for_Data_Discovery_1-3#contributor_name

**Comment by jeffcullis** [comment]
Interesting, so then I guess the template would have to create a new citedResponsibleParty element for each one.

**Comment by n-a-t-e** [comment]
this issue no longer relevant since switching from acdd type structure
