### ISSUE TITLE
changing CI_Party to CI_Individual, CI_Organisation

### ISSUE THREAD

**Issue by n-a-t-e** [cioos-siooc/metadata-xml#8]
We had some CI_Party tags (invalid) that I replaced with CI_Organization or CI_Individual but I wasn't always sure which to use so we should go over that sometime.

**Comment by jeffcullis** [comment]
Based on the table on p. 92 of the ISO19115-1:2014 doc, I think a simple initial test for this would be to check whether positionName is defined, and if so make it a CI_Individual, and if not and a logo is defined, then make it a CI_Organisation, and if neither is true, throw an error and/or omit the party.

**Comment by n-a-t-e** [comment]
After talking to @jeffcullis more about this we can either have  a `type` for each variable (eg `creator_name_type` ) or we can do what ERDDAP does and just hardcode the variables as either Individual or Organization.

eg in ERDDAP:
`creator_name` -> individual
`contributor_name ` -> organisation

I've gone with the second option for now, can change later

**Comment by n-a-t-e** [comment]
`publisher_name`,`publisher_email`, `publisher_country` are under individual as well so far

**Comment by n-a-t-e** [comment]
I didn't notice before that `creator_type` and `publisher_type` exist already in ACDD, defined as:

_one of the following: 'person', 'group', 'institution', or 'position'. If this attribute is not specified, the publisher is assumed to be a person._

http://wiki.esipfed.org/index.php/Attribute_Convention_for_Data_Discovery_1-3#creator_type

**Comment by jeffcullis** [comment]
That's good to know, thanks Nate for clarifying the logic around this.

**Comment by n-a-t-e** [comment]
this issue no longer relevant since switching from acdd type structure
