### ISSUE TITLE
Allow setting of TopicCategoryCode to something other then oceans

### ISSUE THREAD

**Issue by fostermh** [cioos-siooc/metadata-xml#82]
Currently `TopicCategoryCode` is hard-coded to `oceans`. Any chance we could get a parameter in there instead so we can override the hard-coded value? It could still default to `oceans` if needed. 

https://github.com/cioos-siooc/metadata-xml/blob/faea417830c2b626704f755e64479a5a72d43726/metadata_xml/iso19115-cioos-template/main.j2#L270

**Comment by n-a-t-e** [comment]
Could do, these are the options btw:

```
biota
boundaries
climatologyMeteorologyAtmosphere
disaster
economy
elevation
environment
extraTerrestrial
farming
geoscientificInformation
health
imageryBaseMapsEarthCover
inlandWaters
intelligenceMilitary
location
oceans
planningCadastre
society
structure
transportation
utilitiesCommunication
```
See all the descriptions here: https://wiki.esipfed.org/ISO_19115-3_Codelists#MD_TopicCategoryCode

Is this for the metadata form?

**Comment by fostermh** [comment]
will be used as part of the iso19139 to iso19115 conversion at Hakai. It will likely also be helpful for other groups using the metadata form in the future. I also envision CIOOS not hardcoding this value one day but we will see. For example 'oceans' doesn't always make sense for weather stations, for example.
