### ISSUE TITLE
progress_code vs status?

### ISSUE THREAD

**Issue by fostermh** [cioos-siooc/metadata-xml#87]
are progress_code and status the same thing?

https://github.com/cioos-siooc/metadata-xml/blob/d551644f21c8f2167d6b9cfd093f888470cfb299/metadata_xml/iso19115-cioos-template/main.j2#L432

https://github.com/cioos-siooc/metadata-xml/blob/d551644f21c8f2167d6b9cfd093f888470cfb299/metadata_xml/iso19115-cioos-template/main.j2#L277

**Comment by n-a-t-e** [comment]
Good catch, these should both be `record['identification']['progress_code']`. Also looks like the metadata form isn't populating `progress_code`
