### ISSUE TITLE
Create translation text

### ISSUE THREAD

**Issue by jeffcullis** [cioos-siooc/metadata-xml#90]
The metadata entry form allows users to create translations for entries as they enter them. However, in cases where the YAML is being generated programmatically there is no scalable way to add the translation text. Would be good to have an option to create translated text for the title and abstract in output YAML and XML files.
https://docs.aws.amazon.com/translate/latest/dg/examples-python.html

**Comment by n-a-t-e** [comment]
Are the users that need this OK with setting up their own AWS account? Not sure how this would work in a way that doesn't expose our AWS account info

**Comment by n-a-t-e** [comment]
I think for the case of programmatic record creation, the user could set this up by doing the API calls themself, and then running this package with the translated text as input
