### ISSUE TITLE
linebreaks are not kept

### ISSUE THREAD

**Issue by ogsletcax** [cioos-siooc/metadata-xml#93]
some fields (like the abstract field) are likely to be formated with linebreaks by a user in the metadaform.

unfortunatly this linebreaks are removed in the xml file. 

i guess it happens here: https://github.com/cioos-siooc/metadata-xml/blob/638c3f6fb59baa2a8e4741fe3548d3754362c6db/metadata_xml/template_functions.py#L96

can we change that behaviour to keep linebreaks?

@n-a-t-e

**Comment by ogsletcax** [comment]
Update: The catalog interprets markdown, we noticed that we can have proper line breaks in the catalogue by adding double spacing before the end of a line. We can use this workaround for now but it s not user friendly.

**Comment by sjbruce** [comment]
This could be an optional setting and add it via RegEx or some kind of search & replace.  There probably aren't that many fields that would need such a treatment.

**Comment by n-a-t-e** [comment]
Its surprisingly difficult to prettifying this XML in the right way. I've tried the `BeautifulSoup.prettify`, `etree`'s `pretty_print`, and lxml prettify. 

None of those worked, but `ET.indent(element)` worked perfectly and is a one liner. The only downside is it requires Python 3.9.  Does anyone that uses this tool directly mind if they need to use Python 3.9?
