### ISSUE TITLE
Erddap resources don't use name and description provided in the metadata form

### ISSUE THREAD

**Issue by ogsletcax** [cioos-siooc/metadata-xml#98]
Erddap resources don't use name and description provided in the metadata form. Only defaults are set:

name: ERDDAP Data Subset Form
description: ERDDAP's version of the OPeNDAP .html web page for this dataset. Specify a subset of the dataset and download the data via OPeNDAP or in many different file types.

This specific behaviour is coded here:
https://github.com/cioos-siooc/metadata-xml/blob/ee3a159702408f38582329db459a0a69dbd73d68/metadata_xml/iso19115-cioos-template/main.j2#L643

Is this still usefull to use these defaults? if it is, is it ok to use the name and description provided by the form?

@n-a-t-e @fostermh @jeffcullis

**Comment by n-a-t-e** [comment]
I agree that it makes sense to use the resource's name, URL, and description here.

This is what it currently looks like in CKAN for all erddap datasets:
![Screen Shot 2022-03-08 at 9 25 09 AM](https://user-images.githubusercontent.com/26209011/157292401-77ed09c4-9bc7-4f2b-992c-3bfeeb3bbd20.png)

Here is an example of some text that would be used instead for a dataset (description is optional so will probably be empty most of the time):

![Screen Shot 2022-03-08 at 9 27 01 AM](https://user-images.githubusercontent.com/26209011/157292394-bce65494-acc3-43ff-b8dd-2a6a68a915c8.png)

**Comment by fostermh** [comment]
I can't see why we wouldn't use the entries from the metadata form. to be clear this is a 'how the xml is generated' issue? not how it is displayed? ie. I think ckan is just showing whatever is currently in the xml.

**Comment by n-a-t-e** [comment]
> I can't see why we wouldn't use the entries from the metadata form. to be clear this is a 'how the xml is generated' issue? not how it is displayed? ie. I think ckan is just showing whatever is currently in the xml.

yes, this is just an XML issue not a CKAN issue
